# Generated by Django 4.0.6 on 2022-07-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dni', models.BigIntegerField(max_length=8, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=35)),
                ('apellido_materno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'FEemenino'), ('M', 'Masculino')], max_length=1)),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dni', models.BigIntegerField(max_length=8, primary_key=True, serialize=False)),
                ('apellido_paterno', models.CharField(max_length=35)),
                ('apellido_materno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'FEemenino'), ('M', 'Masculino')], max_length=1)),
                ('vigencia', models.BooleanField()),
                ('codigo_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.docente'),
        ),
    ]
