# Generated by Django 4.0.6 on 2022-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.PositiveSmallIntegerField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.PositiveIntegerField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.PositiveBigIntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.PositiveBigIntegerField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_matricula',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
