# Generated by Django 4.0.6 on 2022-07-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_carrera_codigo_alter_curso_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docente',
            name='dni',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
