# Generated by Django 4.0.6 on 2022-07-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_estudiante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
