# Generated by Django 4.0.6 on 2022-07-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_matricula_id_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
